# Generated by Django 3.2.6 on 2021-09-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('blog_post', models.TextField()),
                ('auther_name', models.CharField(max_length=50)),
                ('pub_date', models.CharField(max_length=10)),
            ],
        ),
    ]
