# Generated by Django 3.2.7 on 2021-09-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('phone', models.CharField(max_length=13)),
            ],
        ),
    ]
